import json
import os
from main import CodebaseGenius
from datetime import datetime

def test_multiple_repositories():
    """Test Codebase Genius with multiple repositories and generate sample outputs"""
    
    # Test repositories - choose diverse examples
    test_repos = [
        {
            "name": "jac-demo",
            "url": "https://github.com/jaseci-labs/jac-demo",
            "description": "Simple Jac language demo - good for testing basic functionality"
        },
        {
            "name": "flask-tutorial", 
            "url": "https://github.com/microsoft/python-sample-vscode-flask-tutorial",
            "description": "Python Flask web app - good for testing web frameworks"
        },
        {
            "name": "simple-python",
            "url": "https://github.com/jakevdp/simple-python-example",
            "description": "Simple Python package - good for testing package structure"
        }
    ]
    
    genius = CodebaseGenius()
    results = []
    
    print("🚀 Starting Multi-Repository Test Suite")
    print("=" * 60)
    
    for i, repo in enumerate(test_repos, 1):
        print(f"\n📁 Test {i}/{len(test_repos)}: {repo['name']}")
        print(f"   URL: {repo['url']}")
        print(f"   Desc: {repo['description']}")
        print("-" * 40)
        
        try:
            # Analyze the repository
            result = genius.analyze_repository(repo['url'])
            
            # Add repo info to result
            result['test_info'] = {
                'test_name': repo['name'],
                'description': repo['description'],
                'timestamp': datetime.now().isoformat()
            }
            
            results.append(result)
            
            if result['status'] == 'completed':
                print(f"✅ SUCCESS: {repo['name']}")
                print(f"   📊 Files: {result['summary']['files_analyzed']}")
                print(f"   📝 Functions: {result['summary']['functions_found']}")
                print(f"   🏛️ Classes: {result['summary']['classes_found']}")
                print(f"   💾 Docs saved: {result['documentation_path']}")
            else:
                print(f"❌ FAILED: {repo['name']}")
                print(f"   Error: {result.get('error', 'Unknown error')}")
                
        except Exception as e:
            error_result = {
                'status': 'error',
                'error': str(e),
                'test_info': {
                    'test_name': repo['name'],
                    'description': repo['description'],
                    'timestamp': datetime.now().isoformat()
                }
            }
            results.append(error_result)
            print(f"💥 EXCEPTION: {repo['name']}")
            print(f"   Error: {e}")
    
    # Save comprehensive test results
    test_output_path = "../outputs/test_results.json"
    os.makedirs(os.path.dirname(test_output_path), exist_ok=True)
    
    with open(test_output_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2)
    
    print("\n" + "=" * 60)
    print("🎯 TEST SUITE COMPLETED")
    
    # Generate summary
    successful = [r for r in results if r['status'] == 'completed']
    failed = [r for r in results if r['status'] == 'error']
    
    print(f"✅ Successful: {len(successful)}/{len(test_repos)}")
    print(f"❌ Failed: {len(failed)}/{len(test_repos)}")
    print(f"📊 Results saved to: {test_output_path}")
    
    # Show sample output locations
    if successful:
        print("\n📁 GENERATED DOCUMENTATION:")
        for result in successful:
            print(f"   📄 {result['repository']}: {result['documentation_path']}")
    
    return results

def create_sample_readme():
    """Create a sample README file showing how to use the generated outputs"""
    
    sample_content = """# Codebase Genius - Sample Outputs

This directory contains sample outputs generated by Codebase Genius for various repositories.

## Generated Documentation

The following documentation files were automatically generated:

### 1. jac-demo Documentation
- **Repository**: https://github.com/jaseci-labs/jac-demo
- **Description**: Simple Jac language demonstration
- **Output File**: `jac-demo_docs.md`

### 2. Flask Tutorial Documentation  
- **Repository**: https://github.com/microsoft/python-sample-vscode-flask-tutorial
- **Description**: Python Flask web application tutorial
- **Output File**: `flask-tutorial_docs.md`

### 3. Simple Python Example Documentation
- **Repository**: https://github.com/jakevdp/simple-python-example
- **Description**: Simple Python package structure example
- **Output File**: `simple-python_docs.md`

## Test Results

Comprehensive test results are available in:
- `test_results.json` - Detailed analysis results for all test repositories

## How to Reproduce

To generate similar documentation for any GitHub repository:

```bash
cd BE
python main.py